# Generated by Django 4.1.2 on 2022-11-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
